version: "2"
run:
  build-tags:
    - e2e
  issues-exit-code: 1
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - revive
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/tektoncd/pipeline/vendor/go.uber.org/zap.SugaredLogger).Sync
        - flag.Set
        - os.Setenv
        - logger.Sync
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Closer).Close
        - updateConfigMap
    staticcheck:
      checks:
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
    paths:
      - vendor
      - third_party
      - builtin
      - examples
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party
      - builtin
      - examples
