issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    # temporarily disabling G602 due to https://github.com/securego/gosec/issues/1005
    - path: _test\.go
      linters:
        - gosec
run:
  issues-exit-code: 1
  build-tags:
    - e2e
  skip-dirs:
    - vendor
linters-settings:
  errcheck:
    exclude: .errcheck.txt
  staticcheck:
    checks:
      - '-SA1019' # ignore ClusterTask warning
linters:
  enable:
  - errcheck
  - gofmt
  - goimports
  - gosec
  - gocritic
  - revive
  - misspell
  - unused
