# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/tkn
  binary: tkn
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - s390x
  - ppc64le
  ldflags:
  - -w -X github.com/tektoncd/cli/pkg/cmd/version.clientVersion={{.Version}}
archives:
- name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
release:
  prerelease: true
brews:
  -
    name: tektoncd-cli
    tap:
      owner: tektoncd
      name: homebrew-tools
    folder: Formula
    homepage: "https://github.com/tektoncd/cli"
    description: Tekton CLI - The command line interface for interacting with Tekton
    test: |
      system "#{bin}/tkn", "version"
    install: |
      bin.install_symlink "tkn" => "kubectl-tkn"
      bin.install "tkn" => "tkn"
      output = Utils.popen_read("SHELL=bash #{bin}/tkn completion bash")
      (bash_completion/"tkn").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/tkn completion zsh")
      (zsh_completion/"_tkn").write output
      prefix.install_metafiles
nfpms:
  - file_name_template: "tektoncd-cli-{{.Version}}_{{.Os}}-{{.Arch}}"
    homepage: https://github.com/tektoncd/cli/
    description: A command line interface for interacting with Tekton
    maintainer: Tekton Developers <tekton@tekton.dev>
    license: Apache 2.0
    vendor: Tekton Developers
    formats:
    - deb
    - rpm
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows

universal_binaries:
- replace: true
  name_template: 'tkn'
