# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/tkn
  binary: tkn
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - s390x
  - ppc64le
  ldflags:
  - -w -X github.com/tektoncd/cli/pkg/cmd/version.clientVersion={{.Version}}
archives:
- name_template: >-
    {{- .Binary }}_
    {{- .Version }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else if eq .Arch "arm64" }}aarch64
    {{- else }}{{ .Arch }}{{ end }}
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
release:
  prerelease: "true"
brews:
  - name: tektoncd-cli
    repository:
      owner: tektoncd
      name: homebrew-tools
    directory: Formula
    homepage: "https://github.com/tektoncd/cli"
    description: Tekton CLI - The command line interface for interacting with Tekton
    test: |
      system "#{bin}/tkn", "version"
    install: |
      bin.install_symlink "tkn" => "kubectl-tkn"
      bin.install "tkn" => "tkn"
      output = Utils.popen_read("SHELL=bash #{bin}/tkn completion bash")
      (bash_completion/"tkn").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/tkn completion zsh")
      (zsh_completion/"_tkn").write output
      prefix.install_metafiles
nfpms:
  - file_name_template: >-
      tektoncd-cli-
      {{- .Version }}_
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    homepage: https://github.com/tektoncd/cli/
    description: A command line interface for interacting with Tekton
    maintainer: Tekton Developers <tekton@tekton.dev>
    license: Apache 2.0
    vendor: Tekton Developers
    formats:
    - deb
    - rpm
    bindir: /usr/bin
universal_binaries:
- replace: true
  name_template: 'tkn'
