apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-versions
spec:
  workspaces:
    - name: source
      mountPath: /workspace/src/$(params.package)
  params:
    - name: package
      description: base package where the source code lies
  steps:
    - name: pull-get-versions
      image: alpine/git:v2.40.1
      workingDir: $(workspaces.source.path)
      script: |
        git config --global --add safe.directory $(workspaces.source.path)
        git status && git fetch -p --all
        echo -n $(git tag --points-at HEAD) > $(results.version.path)
        echo -n $(git tag --points-at HEAD | sed 's/^v\([^\.]*\)\.\([^\.]*\).*/\1/') > $(results.major.path)
        echo -n $(git tag --points-at HEAD | sed 's/^v\([^\.]*\)\.\([^\.]*\).*/\2/') > $(results.minor.path)
  results:
    - name: version
    - name: major
    - name: minor
