apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goreleaser
spec:
  workspaces:
    - name: source
      mountPath: /workspace/src/$(params.package)
  params:
    - name: package
      description: base package to build in
    - name: github-token-secret
      description: name of the secret holding the github-token
      default: bot-token-github
    - name: github-token-secret-key
      description: name of the secret key holding the github-token
      default: bot-token
    - name: flags
      description: flags to use for the test command
      default: --timeout=30m
  steps:
    - name: pull
      image: goreleaser/goreleaser:v0.132
      workingdir: $(workspaces.source.path)
      script: |
        git status; git fetch -p --all
    - name: release
      image: goreleaser/goreleaser
      workingdir: $(workspaces.source.path)
      script: |
        goreleaser release $(params.flags)
      env:
        - name: GOPATH
          value: /workspace
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.github-token-secret)
              key: $(params.github-token-secret-key)
