---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cli-release-pipeline
spec:
  params:
  - name: package
    description: package to release
    default: github.com/tektoncd/cli
  - name: github-token-secret
    description: name of the secret holding the github-token
    default: bot-token-github
  - name: github-token-secret-key
    description: name of the key for the secret holding the github-token
    default: bot-token
  resources:
  - name: source
    type: git
  tasks:
    - name: get-versions
      resources:
        inputs:
        - name: source
          resource: source
      taskRef:
        name: get-versions
    - name: lint
      runAfter: [get-versions]
      taskRef:
        name: golangci-lint
      params:
      - name: package
        value: $(params.package)
      - name: flags
        value: "-v --timeout 10m"
      - name: version
        value: v1.24.0
      resources:
        inputs:
        - name: source
          resource: source
    - name: unit-tests
      runAfter: [lint]
      taskRef:
        name: golang-test
      params:
        - name: package
          value: $(params.package)
        - name: version
          value: 1.13.8
        - name: flags
          value: -v -mod=vendor
      resources:
        inputs:
          - name: source
            resource: source
    - name: build
      runAfter: [lint]
      taskRef:
        name: golang-build
      params:
        - name: package
          value: $(params.package)
        - name: version
          value: 1.13.8
        - name: flags
          value: -v -mod=vendor
      resources:
        inputs:
          - name: source
            resource: source
    - name: publish
      runAfter: [build, unit-tests]
      taskRef:
        name: kaniko-build-and-push
      params:
      - name: DOCKERFILE
        value: contrib/tkn-image/Dockerfile
      - name: EXTRA_ARGS
        value:
        - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:latest
        - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:$(tasks.get-versions.results.version)
        - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v$(tasks.get-versions.results.major)
        - --destination=gcr.io/tekton-releases/github.com/tektoncd/cli/cmd/tkn:v$(tasks.get-versions.results.major).$(tasks.get-versions.results.minor)
        - --destination=gcr.io/tekton-releases/tkn:latest
        - --destination=gcr.io/tekton-releases/tkn:$(tasks.get-versions.results.version)
        - --destination=gcr.io/tekton-releases/tkn:v$(tasks.get-versions.results.major)
        - --destination=gcr.io/tekton-releases/tkn:v$(tasks.get-versions.results.major).$(tasks.get-versions.results.minor)
      resources:
        inputs:
        - name: source
          resource: source
    - name: release
      runAfter: [build, unit-tests]
      taskRef:
        name: goreleaser
      params:
      - name: package
        value: $(params.package)
      - name: github-token-secret
        value: $(params.github-token-secret)
      - name: github-token-secret-key
        value: $(params.github-token-secret-key)
      resources:
        inputs:
        - name: source
          resource: source
