---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rpmbuild
spec:
  resources:
    inputs:
      - name: source
        type: git
        targetPath: src
  steps:
  - name: build-rpm
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: bot-token-github
          key: bot-token
    - name: COPR_TOKEN
      valueFrom:
        secretKeyRef:
          name: copr-cli-config
          key: copr
    image: quay.io/chmouel/rpmbuild
    workingdir: /workspace/src
    command: ["tekton/rpmbuild/build.sh"]
