---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: rpmbuild-taskrun
spec:
  taskRef:
    kind: Task
    name: rpmbuild
  resources:
    inputs:
      - name: source
        resourceSpec:
          type: git
          params:
            - name: revision
              value: master
            - name: url
              value: https://github.com/tektoncd/cli
