name: Slash Command Routing

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
    - name: route-land
      uses: peter-evans/slash-command-dispatch@9bdcd7914ec1b75590b790b844aa3b8eee7c683a # v5.0.2
      with:
        token: ${{ secrets.CHATOPS_TOKEN }}
        config: >
          [
            {
              "command": "retest",
              "permission": "write",
              "issue_type": "pull-request",
              "repository": "tektoncd/cli"
            },
            {
              "command": "cherry-pick",
              "permission": "write",
              "issue_type": "pull-request",
              "repository": "tektoncd/cli"
            },
            {
              "command": "rebase",
              "permission": "write",
              "issue_type": "pull-request",
              "repository": "tektoncd/cli"
            }
          ]
